# Generated by Django 4.2.7 on 2023-11-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Create_job_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ctc', models.IntegerField()),
                ('deadline', models.DateField(auto_now_add=True)),
                ('cgpa_cutoff', models.FloatField()),
                ('role', models.CharField(max_length=15)),
                ('CSE', models.BooleanField(default=False)),
                ('ISE', models.BooleanField(default=False)),
                ('ECE', models.BooleanField(default=False)),
                ('EEE', models.BooleanField(default=False)),
                ('MECH', models.BooleanField(default=False)),
                ('CIVIL', models.BooleanField(default=False)),
            ],
        ),
    ]
