# Generated by Django 4.2.7 on 2023-11-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Create_job_profile',
            new_name='Create_job_offer',
        ),
    ]
