# Generated by Django 4.2.7 on 2023-11-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('password', models.IntegerField()),
            ],
        ),
    ]
