# Generated by Django 4.2.7 on 2023-11-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usn', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('sem', models.IntegerField()),
                ('phone', models.TextField()),
                ('skills', models.TextField()),
                ('password', models.TextField(max_length=10)),
            ],
        ),
    ]
