# Generated by Django 4.2.7 on 2023-11-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sregister',
            name='cgpa',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
